language:
  python

os:
  - linux

python:
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: false

install:
  - pip install -r requirements.txt

script:
  python test.py
