language: python

matrix:
    include:
        - os: linux
          python: 3.7
          env: TOXENV=py37
        - os: windows
          python: 3.7
          env: TOXENV=py37
install:
  - pip install -r requirements.txt

script:
  ./test.py
