language:
  python

os:
  - linux

python:
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: false

install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install nose

script:
  - python ./test/test.py
  - nosetests #--with-coverage

after_success:
  - coveralls
