mangas:
  - url:
      https://www.japscan.to/manga/hajime-no-ippo/
  - url:
      https://www.japscan.to/manga/shingeki-no-kyojin/
  - url:
      https://www.japscan.to/manga/hunter-x-hunter/


destinationPath:
  ./mangas/

mangaFormat:
  pdf
