mangas:
  - chapters:
      url:
         https://www.japscan.to/lecture-en-ligne/black-clover/
      chapter_min:
         158
      chapter_max:
         160

destination_path:
  ./mangas/

manga_format:
  jpg
