mangas:
#  - chapter:
#      https://www.japscan.to/lecture-en-ligne/shingeki-no-kyojin/60/
#  - url:
#      https://www.japscan.to/manga/uq-holder/
#  - chapters:
#      url:
#         https://www.japscan.to/lecture-en-ligne/shingeki-no-kyojin/
#      plagemin:
#         158
#      plagemax:
#         197

  - chapters:
      url:
         https://www.japscan.to/lecture-en-ligne/black-clover/
      plagemin:
         158
      plagemax:
         197

destinationPath:
  ./mangas/

mangaFormat:
  jpg
