usage: main.py [-h] [-c CONFIG_FILE] [-d DESTINATION_PATH] [-f FORMAT] [-v]
               [-R REMOVE]

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG_FILE, --config_file CONFIG_FILE
                        Set config file Example : python
                        japscandownloader/main.py -c /home/myconfigfile.yml
  -d DESTINATION_PATH, --destination_path DESTINATION_PATH
                        Set destination path of downloaded mangas Example :
                        python japscandownloader/main.py -d /home/mymangas/
  -f FORMAT, --format FORMAT
                        Set format of downloaded mangas Example : python
                        japscandownloader/main.py -f cbz
  -v, --verbose         Active verbose mode, support different level Example :
                        python japscandownloader/main.py -vv
  -R REMOVE, --remove REMOVE
                        remove downloaded images (when format is pdf/cbz)
                        (default : true) Example : python
                        japscandownloader/main.py -R false|f|no|n|0
